In [ ]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.12/dist-packages (1.1.2)

In [ ]:
import pandas as pd

from apyori import apriori

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv(
    "Market_Basket_Optimisation.csv",
    header=None
)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
transactions = []

for i in range(
    0,
    len(df)
):

    transactions.append(
        [
            str(df.values[i,j])
            for j in range(20)
        ]
    )

In [ ]:
print(transactions[0])

['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil']

In [ ]:
rules = apriori(
    transactions,
    min_support=0.003,
    min_confidence=0.2,
    min_lift=3,
    min_length=2
)

In [ ]:
results = list(rules)

print(
    "Total Rules:",
    len(results)
)

Total Rules: 160

In [ ]:
results = list(rules)

print(
    "Total Rules:",
    len(results)
)

Total Rules: 0

In [ ]:
for item in results:

    pair = item[0]

    print(
        list(pair)
    )

    print(
        "Support:",
        item[1]
    )

    print(
        "Confidence:",
        item[2][0][2]
    )

    print(
        "Lift:",
        item[2][0][3]
    )

    print("-"*50)

In [ ]:
rule_list = []

for item in results:

    rule_list.append([
        list(item[0]),
        item[1],
        item[2][0][2],
        item[2][0][3]
    ])

rules_df = pd.DataFrame(
    rule_list,
    columns=[
        'Rule',
        'Support',
        'Confidence',
        'Lift'
    ]
)

rules_df.head(10)

Empty DataFrame
Columns: [Rule, Support, Confidence, Lift]
Index: []

In [ ]:
rules_df.sort_values(
    by='Lift',
    ascending=False
).head(10)

Empty DataFrame
Columns: [Rule, Support, Confidence, Lift]
Index: []

In [ ]:
min_confidence=0.2

In [ ]:
rules2 = apriori(
    transactions,
    min_support=0.003,
    min_confidence=0.5,
    min_lift=3,
    min_length=2
)

results2 = list(
    rules2
)

print(
    "Rules after increasing confidence:",
    len(results2)
)

Rules after increasing confidence: 28

In [ ]:
print(
    "Confidence = 0.2:",
    len(results)
)

print(
    "Confidence = 0.5:",
    len(results2)
)

Confidence = 0.2: 0
Confidence = 0.5: 28